// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AdminBookingsListData, AdminBookingsListResponses, AdminMeetingTypesCreateData, AdminMeetingTypesCreateResponses, BookingsCreateData, BookingsCreateErrors, BookingsCreateResponses, MeetingTypesListData, MeetingTypesListResponses, MeetingTypesSlotsData, MeetingTypesSlotsErrors, MeetingTypesSlotsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Предстоящие Записи всех Типов встречи одним списком.
 */
export const adminBookingsList = <ThrowOnError extends boolean = false>(options?: Options<AdminBookingsListData, ThrowOnError>) => (options?.client ?? client).get<AdminBookingsListResponses, unknown, ThrowOnError>({ url: '/api/admin/bookings', ...options });

/**
 * Создать Тип встречи.
 */
export const adminMeetingTypesCreate = <ThrowOnError extends boolean = false>(options: Options<AdminMeetingTypesCreateData, ThrowOnError>) => (options.client ?? client).post<AdminMeetingTypesCreateResponses, unknown, ThrowOnError>({
    url: '/api/admin/meeting-types',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Записаться на свободный слот.
 */
export const bookingsCreate = <ThrowOnError extends boolean = false>(options: Options<BookingsCreateData, ThrowOnError>) => (options.client ?? client).post<BookingsCreateResponses, BookingsCreateErrors, ThrowOnError>({
    url: '/api/bookings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Список Типов встречи.
 */
export const meetingTypesList = <ThrowOnError extends boolean = false>(options?: Options<MeetingTypesListData, ThrowOnError>) => (options?.client ?? client).get<MeetingTypesListResponses, unknown, ThrowOnError>({ url: '/api/meeting-types', ...options });

/**
 * Свободные слоты Типа встречи в окне записи.
 */
export const meetingTypesSlots = <ThrowOnError extends boolean = false>(options: Options<MeetingTypesSlotsData, ThrowOnError>) => (options.client ?? client).get<MeetingTypesSlotsResponses, MeetingTypesSlotsErrors, ThrowOnError>({ url: '/api/meeting-types/{id}/slots', ...options });
