// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://contract` | (string & {});
};

/**
 * Запись гостя на конкретное время.
 */
export type Booking = {
    id: number;
    meetingTypeId: number;
    startsAt: string;
    endsAt: string;
    guestName: string;
    guestEmail: string;
};

/**
 * Данные для создания Записи.
 */
export type BookingInput = {
    meetingTypeId: number;
    startsAt: string;
    guestName: string;
    guestEmail: string;
};

/**
 * Заготовка разговора, которую заводит владелец.
 */
export type MeetingType = {
    id: number;
    title: string;
    description: string;
    durationMinutes: number;
};

/**
 * Данные для создания Типа встречи.
 */
export type MeetingTypeInput = {
    title: string;
    description: string;
    durationMinutes: number;
};

/**
 * Ресурс не найден.
 */
export type NotFoundError = {
    code: 'not_found';
    message: string;
};

/**
 * Отрезок рабочего времени, на который можно записаться.
 */
export type Slot = {
    startsAt: string;
    endsAt: string;
};

/**
 * Свободные слоты Типа встречи вместе с таймзоной, в которой их показывать.
 */
export type SlotList = {
    timezone: string;
    slots: Array<Slot>;
};

/**
 * Слот заняли между показом и отправкой формы.
 */
export type SlotTakenError = {
    code: 'slot_taken';
    message: string;
};

export type AdminBookingsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/bookings';
};

export type AdminBookingsListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<Booking>;
};

export type AdminBookingsListResponse = AdminBookingsListResponses[keyof AdminBookingsListResponses];

export type AdminMeetingTypesCreateData = {
    body: MeetingTypeInput;
    path?: never;
    query?: never;
    url: '/api/admin/meeting-types';
};

export type AdminMeetingTypesCreateResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: MeetingType;
};

export type AdminMeetingTypesCreateResponse = AdminMeetingTypesCreateResponses[keyof AdminMeetingTypesCreateResponses];

export type BookingsCreateData = {
    body: BookingInput;
    path?: never;
    query?: never;
    url: '/api/bookings';
};

export type BookingsCreateErrors = {
    /**
     * An unexpected error response.
     */
    default: SlotTakenError | NotFoundError;
};

export type BookingsCreateError = BookingsCreateErrors[keyof BookingsCreateErrors];

export type BookingsCreateResponses = {
    /**
     * The request has succeeded and a new resource has been created as a result.
     */
    201: Booking;
};

export type BookingsCreateResponse = BookingsCreateResponses[keyof BookingsCreateResponses];

export type MeetingTypesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/meeting-types';
};

export type MeetingTypesListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<MeetingType>;
};

export type MeetingTypesListResponse = MeetingTypesListResponses[keyof MeetingTypesListResponses];

export type MeetingTypesSlotsData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        from: string;
        to: string;
    };
    url: '/api/meeting-types/{id}/slots';
};

export type MeetingTypesSlotsErrors = {
    /**
     * An unexpected error response.
     */
    default: NotFoundError;
};

export type MeetingTypesSlotsError = MeetingTypesSlotsErrors[keyof MeetingTypesSlotsErrors];

export type MeetingTypesSlotsResponses = {
    /**
     * The request has succeeded.
     */
    200: SlotList;
};

export type MeetingTypesSlotsResponse = MeetingTypesSlotsResponses[keyof MeetingTypesSlotsResponses];
